/// this is detail page it is not compleate needs to finsish link to checkout page wait for log-in page and enpoint

import { useParams, useSearchParams } from "next/navigation";
import Head from "next/head";
import { useEffect, useState } from "react";
export default function About() {
    /// take out the id from url for generting dynamicly the pages
    var id = useSearchParams().get('id')
    var [detailData, sedetaiData] = useState(undefined);
    //// fetching data for a good which has been asked with good id
    useEffect(function () {
        fetch('/api/findbyid/' + id)
            .then(function (responde) {
                console.log(responde);
                if (responde.status != 404) {
                    responde.json()
                        .then(function (data) {
                            sedetaiData(data);
                        })
                        .catch(function (er) {
                            window.alert('something wrong with json');
                            console.log(er);
                        })
                }
                if (responde.status == 404) {
                    window.alert('no data find')
                }
            })
            .catch(function (er) {
                console.log(er);
                window.alert('something wrong with connection');
            })
    }, [])
    return (
        <>
            <Head>
                <title>Create Next App2</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="description" content="source is https://bootdey.com/snippets/view/bs4-product-detail#html,https://getbootstrap.com" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
              {/*displaying the details for the goods asked*/}
            {detailData != undefined && (
                
                <>
                    <div className="container">
                        <div className="card">
                            <div className="card-body">
                                <h3 className="card-title">{detailData.name}</h3>
                                {/* <h6 className="card-subtitle">globe type chair for rest</h6> */}
                                <div className="row">
                                    <div className="col-lg-5 col-md-5 col-sm-6">
                                        <div className="white-box text-center">
                                           {detailData.picture!=undefined && <img src="#" className="img-responsive" />}

                                        </div>
                                    </div>
                                    <div className="col-lg-7 col-md-7 col-sm-6">
                                        <h4 className="box-title mt-5">Product description</h4>
                                        {detailData.description.description!=undefined&&<p> {detailData.description.description}</p>}
                                        {detailData.description.description==undefined&&<p> no data</p>}
                                        <h2 className="mt-5">
                                           {detailData.price!=undefined && <p>{detailData.price} </p>}
                                           {detailData.price==undefined && <p> no price to show </p>}
                                        </h2>
                                        <button className="btn btn-dark btn-rounded mr-1" data-toggle="tooltip" title="" data-original-title="Add to cart">
                                            <i className="fa fa-shopping-cart"></i>
                                        </button>
                                        <button className="btn btn-primary btn-rounded">Buy Now</button>
                                        {/* <h3 className="box-title mt-5">Key Highlights</h3>
                                        <ul className="list-unstyled">
                                            <li><i className="fa fa-check text-success"></i>Sturdy structure</li>
                                            <li><i className="fa fa-check text-success"></i>Designed to foster easy portability</li>
                                            <li><i className="fa fa-check text-success"></i>Perfect furniture to flaunt your wonderful collectibles</li>
                                        </ul> */}
                                    </div>
                                    <div className="col-lg-12 col-md-12 col-sm-12">
                                        <h3 className="box-title mt-5">General Info</h3>
                                        <div className="table-responsive">
                                            <table className="table table-striped table-product">
                                                <tbody>
                                                    <tr>
                                                        <td width="390">price</td>
                                                       {detailData.price!=undefined && <td>{detailData.price}</td>}
                                                       {detailData.price==undefined && <td> no price</td>}
                                                    </tr>
                                                    <tr>
                                                        <td>color</td>
                                                        {detailData.description.color!=undefined &&(<td>{detailData.description.color}</td>)}
                                                        {detailData.description.color==undefined &&(<td>no color</td>)}
                                                    </tr>
                                                    <tr>
                                                        <td>size</td>
                                                       { detailData.description.size!=undefined &&(<td>{detailData.description.size}</td>)}
                                                       {detailData.description.size==undefined &&(<td>no size</td>)}
                                                    </tr>
                                                    <tr>
                                                        <td>category</td>
                                                        { detailData.category!=undefined &&(<td>{detailData.category}</td>)}
                                                        {detailData.category==undefined &&(<td> no data </td>)}
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </>
            )}

        </>
    )
}