
///this is main page
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState, useEffect } from "react";
import { useSession } from 'next-auth/react';
var tyrunforDispalay = 0;
export default function Home() {
  
  // change login link to user name 
  const { data: session, status } = useSession();

  


  return (
    <>
    {/*head for main page*/}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="source is https://bootdey.com/snippets/view/bs4-product-detail#html,https://getbootstrap.com" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/*showing the top page*/}
      <header>
        <div className="collapse bg-dark" id="navbarHeader" style={{ display: display }}>
          <div className="container">
            <div className="row">
              <div className="col-sm-8 col-md-7 py-4">
                <h4 className="text-white">About</h4>
                <p className="text-muted">store information </p>
              </div>
              <div className="col-sm-4 offset-md-1 py-4">
                <h4 className="text-white">Contact</h4>
                <ul className="list-unstyled">
                    {/*link to log in page*/}
                     {/* change login link to user name  */}
                    {session ? (
                    <li>
                      <Link href="/profile">
                        <a className="text-white">{session.user.name}</a>
                      </Link>
                    </li>
                  ) : (
                    <li>
                      <Link href="/signin">
                        <a className="text-white">log in(connect to login) page</a>
                      </Link>
                    </li>
                  )}                </ul>
              </div>
                {/*serach which trigger the clickfuction for serching*/}
              <form className="form-inline mt-2 mt-md-0">
                <input className="form-control mr-sm-2" type="text" onChange={function (e) {
                  clickfunctionforserch(e.target.value);
                }} />

              </form>
            </div>
          </div>
        </div>
        <div className="navbar navbar-dark bg-dark box-shadow">
          <div className="container d-flex justify-content-between">
            <a href="#" className="navbar-brand d-flex align-items-center">
              <strong>Album</strong>
            </a>
            {/* triger the display function for showing the header */}
            <button className="navbar-toggler" onClick={function () { displayMenue() }}>
              <span className="navbar-toggler-icon"></span>
            </button>
          </div>
        </div>
      </header>
        {/*showing the sreach which has been find*/}
      <main role="main">
     
      </main>
    </>
  );
}
